### ISSUE TITLE
Unable to Create Encounter

### ISSUE THREAD

**Issue by CoryOwens** [mouse0270/Beyonds-Toolbox#18]
I am unable to create an encounter with either the Custom Monster button or the button included on monster pages. In the Encounter Builder dialog, the Encounter dropdown is populated only with `{0}`, and whether I select that or type in a new encounter name, the Add button does nothing. The dialog stays open, and the Encounters list in the side bar remains empty.

**Comment by mouse0270** [comment]
If you hit, F12 on your keyboard and select "console" do you see any errors being reported by google chrome.

**Comment by CoryOwens** [comment]
```
Error in response to storage.get: TypeError: Toolbox.settings.encounters.forEach is not a function
    at Object.callback (chrome-extension://fffggleecacldpcipbechibchfikglgh/scripts/toolbox.loader.js:170:44)
    at _Loader.encounters (chrome-extension://fffggleecacldpcipbechibchfikglgh/scripts/toolbox.loader.js:165:23)
    at _Loader.build (chrome-extension://fffggleecacldpcipbechibchfikglgh/scripts/toolbox.loader.js:38:12)
    at Object.callback (chrome-extension://fffggleecacldpcipbechibchfikglgh/scripts/toolbox.loader.js:72:18)
```

Other than that, just some failed `GET` requests because I have Facebook blocked.

**Comment by mouse0270** [comment]
Can you try removing the extension and re-adding it?

**Comment by CoryOwens** [comment]
Looks like that resolved it. 

Weird, I thought I tried that. Also, it was happening on multiple computers, so I assume it had something to do with sync.

**Comment by mouse0270** [comment]
Yeah, there is a bug with the sync and encounters. I think I have it patched in the next release. but the next release has some other features. So I am just testing everything as best as a single developer can.

**Comment by CoryOwens** [comment]
Sounds good. If you need beta testers, let me know.

**Comment by mouse0270** [comment]
Just so you know if you know how to load extensions via developers mode on Google Chrome you can always download this repo and it would basically allow you to test upcoming features.

This repo is basically a sorta stable beta. It usually has features that the version on the chrome store doesn't.

For example, this version includes a Custom Character Theme Color picker and the ability to sort skills by clicking on the headings.

It also comes with a BUGGY GitHub Gist Sync option. lol
